Repository JesusSoto7/proyecto-ale-beauty-art, pull requests merged in 2025-04, with the labels that each got.

#2 Backend inicial
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/categoria.rb
  app/models/detalle_orden.rb
  app/models/envio.rb
  app/models/metodo_de_pago.rb
  app/models/orden.rb
  app/models/pago.rb
  app/models/producto.rb
  app/models/rol.rb
  app/models/tono.rb
  app/models/usuario.rb
  config/database.yml
  config/initializers/inflections.rb
  db/migrate/20250415191932_create_roles.rb
  db/migrate/20250415192618_create_usuarios.rb
  db/migrate/20250415200050_create_categorias.rb
  db/migrate/20250415200726_create_productos.rb
  db/migrate/20250415201354_create_tonos.rb
  db/migrate/20250415202213_create_ordenes.rb
  db/migrate/20250415204743_create_detalle_ordenes.rb
  db/migrate/20250415205511_create_metodo_de_pagos.rb
  db/migrate/20250415210535_create_pagos.rb
  db/migrate/20250415212149_create_envios.rb
  db/schema.rb
  docker-compose.yml
  test/fixtures/categorias.yml
  test/fixtures/detalle_ordenes.yml
  test/fixtures/envios.yml
  test/fixtures/metodo_de_pagos.yml
  test/fixtures/ordenes.yml
  test/fixtures/pagos.yml
  test/fixtures/productos.yml
  test/fixtures/roles.yml
  test/fixtures/tonos.yml
  test/fixtures/usuarios.yml
  test/models/categoria_test.rb
  test/models/detalle_orden_test.rb
  test/models/envio_test.rb
  test/models/metodo_de_pago_test.rb
  test/models/orden_test.rb
  test/models/pago_test.rb
  test/models/producto_test.rb
  test/models/rol_test.rb
  test/models/tono_test.rb
  test/models/usuario_test.rb
Labels: enhancement

#4 ajustes
  app/models/categoria.rb
  app/models/orden.rb
  app/models/producto.rb
  docker-compose.yml
Labels: documentation

#12 eliminar migraciones
  app/models/categoria.rb
  app/models/detalle_orden.rb
  app/models/envio.rb
  app/models/metodo_de_pago.rb
  app/models/orden.rb
  app/models/pago.rb
  app/models/producto.rb
  app/models/rol.rb
  app/models/tono.rb
  app/models/usuario.rb
  config/initializers/inflections.rb
  db/migrate/20250415191932_create_roles.rb
  db/migrate/20250415192618_create_usuarios.rb
  db/migrate/20250415200050_create_categorias.rb
  db/migrate/20250415200726_create_productos.rb
  db/migrate/20250415201354_create_tonos.rb
  db/migrate/20250415202213_create_ordenes.rb
  db/migrate/20250415204743_create_detalle_ordenes.rb
  db/migrate/20250415205511_create_metodo_de_pagos.rb
  db/migrate/20250415210535_create_pagos.rb
  db/migrate/20250415212149_create_envios.rb
  db/schema.rb
  test/fixtures/categorias.yml
  test/fixtures/detalle_ordenes.yml
  test/fixtures/envios.yml
  test/fixtures/metodo_de_pagos.yml
  test/fixtures/ordenes.yml
  test/fixtures/pagos.yml
  test/fixtures/productos.yml
  test/fixtures/roles.yml
  test/fixtures/tonos.yml
  test/fixtures/usuarios.yml
  test/models/categoria_test.rb
  test/models/detalle_orden_test.rb
  test/models/envio_test.rb
  test/models/metodo_de_pago_test.rb
  test/models/orden_test.rb
  test/models/pago_test.rb
  test/models/producto_test.rb
  test/models/rol_test.rb
  test/models/tono_test.rb
  test/models/usuario_test.rb
Labels: bug

#14 instalacion y configuracion del devise
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20250423220001_devise_create_users.rb
  db/schema.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement

#16 diagramas
  diagramas.pdf
Labels: enhancement

#15 Mockup del proyecto
  Mockup.pdf
Labels: enhancement

#23 diagramas
  diagramas.pdf
Labels: documentation, wontfix
