Repository JesusSoto7/proyecto-ale-beauty-art, pull requests merged in 2025-05, with the labels that each got.

#30 url drive
  README.md
Labels: enhancement

#36 campo imagen
  diagramas.pdf
Labels: documentation

#32 pagina de Inicio
  app/assets/stylesheets/inicio.css
  app/controllers/inicio_controller.rb
  app/helpers/inicio_helper.rb
  app/views/inicio/index.html.erb
  app/views/layouts/inicio.html.erb
  config/routes.rb
  test/controllers/inicio_controller_test.rb
Labels: enhancement

#44 opcion de omotir inicio de seccion.
  app/assets/stylesheets/sign_in.css
  app/controllers/application_controller.rb
  app/views/devise/sessions/new.html.erb
Labels: enhancement

#46 campos nuevos
  app/assets/stylesheets/sign_up.css
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  db/migrate/20250507041605_add_nombre_apellido_telefono_direccion_to_users.rb
  db/schema.rb
Labels: documentation

#53 Feature/47
  Backend/Gemfile
  Backend/Gemfile.lock
  Backend/app/models/role.rb
  Backend/app/models/user.rb
  Backend/config/initializers/rolify.rb
  Backend/db/migrate/20250508223304_rolify_create_roles.rb
  Backend/db/schema.rb
  Backend/db/seeds.rb
  Backend/test/fixtures/roles.yml
  Backend/test/models/role_test.rb
  Docs/Diagramas/diagramas.pdf
Labels: documentation

#56 terminada las mejoras
  Backend/app/assets/stylesheets/pasword.css
  Backend/app/assets/stylesheets/sign_in.css
  Backend/app/assets/stylesheets/sign_up.css
  Backend/app/views/devise/registrations/new.html.erb
  Backend/app/views/devise/sessions/new.html.erb
  Backend/app/views/inicio/index.html.erb
Labels: enhancement

#58 cerrar sesion
  Backend/app/assets/stylesheets/index.css
  Backend/app/controllers/application_controller.rb
  Backend/app/views/home/index.html.erb
Labels: documentation, enhancement

#70 cerrar sesión terminado
  Backend/app/assets/stylesheets/inicio.css
  Backend/app/views/inicio/index.html.erb
Labels: enhancement

#73 Feature/71
  Backend/app/assets/images/img1.jpg
  Backend/app/assets/images/img2.jpg
  Backend/app/assets/images/img3.jpg
  Backend/app/assets/images/img4.jpg
  Backend/app/assets/images/img5.jpg
  Backend/app/assets/stylesheets/inicio.css
  Backend/app/assets/stylesheets/pasword.css
  Backend/app/assets/stylesheets/sign_in.css
  Backend/app/assets/stylesheets/sign_up.css
  Backend/app/views/devise/passwords/new.html.erb
  Backend/app/views/devise/registrations/new.html.erb
  Backend/app/views/devise/sessions/new.html.erb
  Backend/app/views/inicio/index.html.erb
Labels: enhancement

#74 Feature/69
  Backend/app/assets/stylesheets/inicio.css
  Backend/app/controllers/application_controller.rb
  Backend/app/controllers/home_controller.rb
  Backend/app/views/inicio/index.html.erb
  Backend/app/views/layouts/inicio.html.erb
Labels: enhancement

#83 Feature/78
  Backend/app/assets/stylesheets/productos.css
  Backend/app/assets/stylesheets/sign_in.css
  Backend/app/assets/stylesheets/sign_up.css
  Backend/app/views/devise/passwords/new.html.erb
  Backend/app/views/devise/registrations/new.html.erb
  Backend/app/views/devise/sessions/new.html.erb
  Backend/app/views/inicio/all_products.html.erb
Labels: enhancement
